package live.streamcraft.model.enums;

public enum NotificationType {
	STREAM_STARTED,
    STREAM_ENDED,
    STREAM_SCHEDULED,
    STREAM_REMINDER,
    NEW_FOLLOWER,
    FOLLOW_REQUEST_ACCEPTED,
    SUBSCRIPTION_RENEWAL,
    SUBSCRIPTION_EXPIRING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    CHAT_MENTION,
    USER_BANNED,
    USER_MUTED,
    ROLE_CHANGED,
    ACCOUNT_VERIFIED,
    ACCOUNT_ENABLED,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_CHANGED,
    NEW_MESSAGE,
    STREAM_FEATURED,
    SYSTEM_ALERT,
    MAINTENANCE,
    FEATURE_ANNOUNCEMENT
}
